name: Test API Calls

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run the migration and project tests via rake spec command
        env:
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          WORKER_QUEUE_URL: ${{ secrets.WORKER_QUEUE_URL }}
          DB_FILENAME: db/local/test.db
          RACK_ENV: development
        run: |
          bundle exec rake db:migrate
          bundle exec rake spec
